const url   =  "https://hw.scmxkj.com/hw/";

const api={
	homeBanner:          url+"home/banner",
	homeCamp:            url+"home/camp",
	campInfoDetail:      url+"home/campsite",
	YingDiDetail:        url+"home/camp_info",
	Menu:                url+"home/index_info",
	cateSecond:          url+"home/cate_second",
	out:   				 url+"home/out_pid",
	goodsLists:          url+"product/product",
	goodDetail:          url+"product/product_info",
	shiWuGuiGe:          url+"product/product_kind",
	isCollection:        url+"product/is_collection",
	userID:              url+"index/get_openid",
	addCollection:       url+"product/add_collection",
	addCart:             url+"car/add_car",
	xuniGuiGe:           url+"product/product_spec",
	pakageDetail:        url+"product/package",
	nowBuy:    			 url+"order/add_order",
	getOrder:            url+"order/firm_order",
	pay:                 url+"order/pay_order",
	leaveWords:          url+"order/seller",
	orderLists:          url+"order/order_list",
	cancelOrder:         url+"order/order_delete",
	addAddress:          url+"dress/add_dress",
	addressLists:        url+"dress/index",
	setAddress:          url+"dress/default_dress",
	delAddress:          url+"dress/delete_dress",
	editAddress:         url+"dress/edit_dress",
	cartLists:           url+"car/list_car",
	delCart:             url+"car/del_car",
	CgoPay:              url+"car/pay_car",
	orderAddress:        url+"order/order_dress",
	RaddressEdit:        url+"order/dress_edit",
	COrderConfrim:       url+"car/payment",
	collectionLists:     url+"user/collection",
	delCollection:       url+"user/del_coll",
	orderDetail:         url+"order/order_info",
	campInfo:            url+"home/home_info",
	upDateInfo:          url+"user/user",
	paySuccess:          url+"order/order_status",
	goodsSearch:         url+"product/product_like",
	C:                   url+"user/complan",
	confirmRecive:       url+"order/success_order",
	orderComplan:        url+"order/order_comp",
	more:                url+"home/after",
}

module.exports={
  api: api
}